### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR issue 

### ISSUE THREAD

**Issue by ditoskas** [BenMorel/dev-certificates#2]
Hello man,

Great work with the scripts, but I still have the issue with ERR_SSL_PROTOCOL_ERROR on Chrome Version 86.0.4240.198 (Official Build) (64-bit)
Same for firefox 82.0.3 (64-bit) SSL_ERROR_RX_RECORD_TOO_LONG 

I followed your steps, the ca.crt has been imported on the browsers but when i run the website i am receiving the above errors.
Operating System: Kubuntu Groovy
Nginx: 1.18

I tried the solutions that written on the web (clearing the cache, disabling the browser flags, enable all versions of TLS etc) but without any success. Any idea ?

**Comment by BenMorel** [comment]
Hi, I'm sorry but this doesn't ring a bell. I'd try a browser on which you didn't install the CA first; if you get a similar error, at least you know that the issue is on your web server!
