### ISSUE TITLE
(question) Make wildcard LTD cert's

### ISSUE THREAD

**Issue by Casburggraaf** [BenMorel/dev-certificates#4]
For local development i'm using the {websitename}.test domain. Is it possible to create a single certificate all the .test domains?

**Comment by BenMorel** [comment]
Hi, looking at [this StackOverflow question](https://security.stackexchange.com/q/6873/31331) it looks like although generating such a certificate should be possible, it is unlikely that it would be accepted by any browser (though I don't see `.test` specifically in the linked [Chromium source](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/net/cert/x509_certificate.cc#537)).

However, you can generate & import a CA once in your browser, and then generate one certificate per domain (or group of domains) using this certificate. Sure, you have to generate a certificate when you add a new domain, but at least you only have to configure your browser once!
